export const ultra = [
  ["奥特曼", "ウルトラマン / 初代マン", "Ultraman"],
  ["佐菲", "ゾフィー", "Zoffy"],
  ["赛文·奥特曼", "Ultraseven/ウルトラセブン", "Ultraseven"],
  ["赛文上司", "セブン上司", "Seven's Superior"],
  ["赛文X·奥特曼", "ウルトラセブンX", "Ultraseven X"],
  [
    "杰克·奥特曼",
    "ウルトラマンジャック / 帰ってきたウルトラマン",
    "Ultraman Jack",
  ],
  ["艾斯·奥特曼", "ウルトラマンエース ", "Ultraman Ace"],
  ["奥特之父", "ウルトラの父", "Father of Ultra"],
  ["泰罗·奥特曼", "ウルトラマンタロウ", "Ultraman Taro"],
  ["奥特之母", "ウルトラの母", "Mother of Ultra"],
  ["雷欧·奥特曼", "ウルトラマンレオ", "Ultraman Leo"],
  ["阿斯特拉", "アストラ", "Astra"],
  ["奥特之王", "ウルトラマンキング", "Ultraman King"],
  ["爱迪·奥特曼", "ウルトラマン爱迪", "Ultraman 爱迪"],
  ["尤莉安", "ユリアン", "Yullian"],
  ["梦比优斯·奥特曼", "ウルトラマンメビウス", "Ultraman Mebius"],
  ["希卡利·奥特曼", "ウルトラマンヒカリ", "UItraman Hikari"],
  ["雷欧·奥特曼斯", "ウルトラマンネオス", "Ultraman Neos"],
  ["赛文21·奥特曼", "ウルトラセブン21", "Ultraseven 21"],
  ["麦克斯·奥特曼", "ウルトラマンマックス", "Ultraman Max"],
  ["奥特曼杰诺", "ウルトラマンゼノン", "Ultraman Xenon"],
  ["博伊·奥特曼", "ウルトラマンボーイ", "Ultraman Boy"],
  ["奥特曼利布特", "ウルトラマンリブット", "Ultraman Ribut"],
  ["索拉", "ソラ(ウルトラウーマン) ", "Sora"],
  ["葛雷·奥特曼", "ウルトラマングレート", "Ultraman Great"],
  ["帕瓦特·奥特曼", "ウルトラマンパワード", "Ultraman Powered"],
  ["史考特·奥特曼", "ウルトラマンスコット", "Ultraman Scott"],
  ["奥特曼查克", "ウルトラマンチャック", "Ultraman Chuck"],
  ["奥特曼贝斯", "ウルトラウーマンベス", "Ultrawoman Beth"],
  ["奥特曼乔尼亚斯", "ウルトラマンジョーニアス", "Ultraman Joneus"],
  ["埃米亚", "ロト", "Amia"],
  ["艾雷克", "エレク", "Elek"],
  ["洛特", "アミア", "Loto"],
  ["迪迦·奥特曼", "ウルトラマンティガ", "Ultraman Tiga"],
  ["迪迦之地的石像A、B", "ティガのピラミッドの巨人", "Tiga's companions"],
  ["邪恶迪迦", "イーヴィルティガ", "Evil Tiga[15]"],
  ["爱憎戦士卡蜜拉", "カミーラ", "Camearra"],
  ["刚力戦士达拉姆", "ダーラム", "Darramb"],
  ["俊敏戦士希特拉", "ヒュドラ", "Hudra"],
  ["戴拿·奥特曼", "ウルトラマンダイナ", "Ultraman Dyna"],
  ["人造戴拿", "テラノイド", "Terranoid"],
  ["盖亚·奥特曼", "ウルトラマンガイア", "Ultraman Gaia"],
  ["阿古茹·奥特曼", "ウルトラマンアグル", "Ultraman Agul"],
  ["高斯·奥特曼", "ウルトラマンコスモス", "Ultraman Cosmos"],
  ["杰斯提斯·奥特曼", "ウルトラマンジャスティス", "Ultraman Justice"],
  ["雷杰多·奥特曼", "ウルトラマンレジェンド", "Ultraman Legend"],
  ["奈克斯特·奥特曼", "ウルトラマン・ザ・ネクスト", "Ultraman The Next"],
  ["奈克瑟斯·奥特曼", "ウルトラマンネクサス", "Ultraman Nexus"],
  ["诺亚·奥特曼", "ウルトラマンノア", "Ultraman Noa"],
  ["黑暗浮士德", "ダークファウスト", "Dark Faust"],
  ["黑暗梅菲斯特", "ダークメフィスト", "Dark Mephisto"],
  ["黑暗梅菲斯特II", "ダークメフィスト II", "Dark Mephisto II"],
  ["黑暗扎基", "ダークザギ", "Dark Zagi"],
  ["赛罗·奥特曼", "ウルトラマンゼロ", "Ultraman Zero"],
  ["奥特曼贝利亚", "ウルトラマンベリアル", "Ultraman Belial"],
  ["赛迦·奥特曼", "ウルトラマンサーガ", "Ultraman Saga"],
  ["银河·奥特曼", "ウルトラマンギンガ", "Ultraman Ginga"],
  ["维克特利·奥特曼", "ウルトラマンビクトリー", "Ultraman Victory"],
  [
    "银河維克特利·奥特曼",
    "ウルトラマンギンガビクトリー",
    "Ultraman Ginga Victory",
  ],
  ["艾克斯·奥特曼", "ウルトラマンエックス", "Ultraman X"],
  ["奥特曼欧布", "ウルトラマンオーブ", "Ultraman Orb"],
  ["奥特曼捷德", "ウルトラマンジード", "Ultraman 捷德"],
  ["奥特曼罗索", "ウルトラマンロッソ", "Ultraman Rosso"],
  ["奥特曼布鲁", "ウルトラマンブル", "Ultraman Blu"],
  ["罗布奥特曼", "ウルトラマンルーブ", "Ultraman R / B"],
  ["女奥特曼格丽乔", "ウルトラウーマングリージョ", "Ultrawoman Grigio"],
  ["奥特曼格罗布", "ウルトラマングルーブ", "Ultraman Gruebe"],
  ["泰迦奥特曼", "ウルトラマンタイガ", "Ultraman Taiga"],
  ["奥特曼泰塔斯", "ウルトラマンタイタス", "Ultraman Titas"],
  ["奥特曼风马", "ウルトラマンフーマ", "Ultraman Fuma"],
  ["奥特曼托雷基亚", "ウルトラマントレギア", "Ultraman Tregear"],
  ["奥特曼令河", "ウルトラマンレイガ", "Ultraman Reiga"],
  ["奥特曼杰特", "ウルトラマンゼット", "Ultraman Zett"],
  ["奥特曼特利迦", "ウルトラマントリガー", "Ultraman 特利迦"],
  ["暗黑勇士黑暗特利迦", "トリガーダーク", "特利迦 dark"],
  ["妖丽战士卡尔蜜拉", "妖丽戦士カルミラ", ""],
  ["刚力斗士达贡", "刚力闘士ダーゴン", ""],
  ["俊敏策士希特拉姆", "俊敏策士ヒュドラム", ""],
  ["邪恶特利迦", "イーヴィルトリガー", "特利迦 Evil"],
  ["奥特曼Decker", "ウルトラマンデッカー", "Ultraman Decker"],
  ["哉阿斯·奥特曼", "ウルトラマンゼアス", "Ultraman Zearth"],
  ["影子·奥特曼", "ウルトラマンシャドー", "Ultraman Shadow"],
  ["纳伊斯·奥特曼", "ウルトラマンナイス", "Ultraman Nice"],
  ["雷古洛思奥特曼", "ウルトラマンレグロス", "Ultraman Regulos"],
];
