// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'A': typeof import("../components/A.vue")['default'],
    'C': typeof import("../components/C.vue")['default'],
    'Editor': typeof import("../components/Editor.vue")['default'],
    'Footer': typeof import("../components/Footer.vue")['default'],
    'GridItemA': typeof import("../components/GridItemA.vue")['default'],
    'GridItemB': typeof import("../components/GridItemB.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'Logo': typeof import("../components/Logo.vue")['default'],
    'O': typeof import("../components/O.vue")['default'],
    'W': typeof import("../components/W.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyA': typeof import("../components/A.vue")['default'],
    'LazyC': typeof import("../components/C.vue")['default'],
    'LazyEditor': typeof import("../components/Editor.vue")['default'],
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyGridItemA': typeof import("../components/GridItemA.vue")['default'],
    'LazyGridItemB': typeof import("../components/GridItemB.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyLogo': typeof import("../components/Logo.vue")['default'],
    'LazyO': typeof import("../components/O.vue")['default'],
    'LazyW': typeof import("../components/W.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const A: typeof import("../components/A.vue")['default']
export const C: typeof import("../components/C.vue")['default']
export const Editor: typeof import("../components/Editor.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const GridItemA: typeof import("../components/GridItemA.vue")['default']
export const GridItemB: typeof import("../components/GridItemB.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const O: typeof import("../components/O.vue")['default']
export const W: typeof import("../components/W.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyA: typeof import("../components/A.vue")['default']
export const LazyC: typeof import("../components/C.vue")['default']
export const LazyEditor: typeof import("../components/Editor.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyGridItemA: typeof import("../components/GridItemA.vue")['default']
export const LazyGridItemB: typeof import("../components/GridItemB.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyO: typeof import("../components/O.vue")['default']
export const LazyW: typeof import("../components/W.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
