- name: Setup Node.js environment
  uses: actions/setup-node@v3.3.0
  steps:
    # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
    - name: generate github-contribution-grid-snake.svg
      uses: Platane/snk/svg-only@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          public/github-contribution-grid-snake.svg
          public/github-contribution-grid-snake-dark.svg?palette=github-dark
